DOMAIN: 'diplomat.dev'
MAIL_SENDER: 'no-reply@diplomat.dev'
SECRET_KEY_BASE: ''
SKYLIGHT_AUTHENTICATION: ''
SMTP_SERVER: ''
SMTP_PORT: ''
SMTP_LOGIN: ''
SMTP_PASSWORD: ''

REMOTE_SYSLOG_HOST: ''
REMOTE_SYSLOG_PORT: ''
REMOTE_SYSLOG_LEVEL: 'info'

MQ_URL: 'amqp://guest:guest@localhost:5672'
MQ_MGMT_URL: 'http://guest:guest@localhost:15672'
