default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3

production:
  <<: *default
  database: db/production.sqlite3

irely_default: &default
  adapter: mysql
  host: localhost
  username: westernmilling

irely_development:
  <<: *default
  database: irely_mock

irely_test:
  <<: *default
  database: test_irely_mock

irely_production:
  <<: *default
  database: irely_mock_production
