require_relative 'subscribers/contact.rb'
require_relative 'subscribers/entity.rb'
require_relative 'subscribers/location.rb'
require_relative 'subscribers/organization.rb'
require_relative 'subscribers/salesperson.rb'
