require_relative 'subscribers/contact'
require_relative 'subscribers/customer'
require_relative 'subscribers/entity'
require_relative 'subscribers/location'
require_relative 'subscribers/salesperson'
require_relative 'subscribers/vendor'
